services:
  api:
    image: docker.io/library/spt-development-demo:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://spt-development-demo-db-1:5432/spt-development-demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: p@ssw0rd
      SPRING_ACTIVEMQ_BROKER_URL: tcp://spt-development-demo-activemq-1:61616
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://spt-development-demo-lgtm-1:4318/v1/metrics
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://spt-development-demo-lgtm-1:4318/v1/logs
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://spt-development-demo-lgtm-1:4318/v1/metrics
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://spt-development-demo-lgtm-1:4318/v1/traces
    ports:
      - "8080:8080"
      - "8081:8081"