version: '3.7'

services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: spt-recruitment-demo
    ports:
      - "5432"

  artemis:
    image: apache/activemq-classic:6.1.0
    ports:
      - "61616"
