version: '3.7'

services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: spt-recruitment-demo
    ports:
      - "5432"
