spring:
  application:
    name: SPT Development Demo
  threads:
    virtual:
      enabled: true

logging:
  pattern:
    console: -%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %replace([%X{cid}] ){'\[\] ', ''}%replace(%replace(%msg){'\r', '\\r'}){'\n', '\\n'}%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    access:
      default: read-only
    web:
      exposure:
        include: auditevents,beans,env,flyway,health,info,loggers,metrics,shutdown,startup
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  otlp:
    metrics:
      export:
        # Most of the dashboards available to import use seconds
        base-time-unit: seconds
        step: 10s
  server:
    port: 8081

otel:
  bsp:
    schedule:
      delay: 500
  exporter:
    otlp:
      metrics:
        default:
          histogram:
            # Required for RED Metrics (native) dashboard
            aggregation: BASE2_EXPONENTIAL_BUCKET_HISTOGRAM
  metric:
    export:
      interval: 500

spt:
  audit:
    jms:
      destination: jms.queue.audit-event-queue
  cid:
    web:
      use-request-header: true
  logging:
    dao-support:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: mdc-disabled

spt:
  cid:
    mdc:
      disabled: true