name: spt-development-demo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: mvn clean verify -B

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn clean verify -B

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean verify -B

      - name: Set up JDK 19
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
      - run: mvn clean verify -B

      - name: Set up JDK 19 (MDC disabled)
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
      - run: mvn clean verify -Dspring.profiles.active=mdc-disabled -B
