name: Main Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven - JDK 17
        run: ./mvnw clean verify -B

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Maven - JDK 21
        run: ./mvnw clean verify -B

      - name: Set up JDK 22
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 22

      - name: Run Maven - JDK 22
        run: ./mvnw clean verify -Pall-quality-gates -B

      - name: Set up JDK 22 (MDC Disabled)
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 22

      - name: Run Maven - MDC disabled
        run: ./mvnw clean verify -Dspring.profiles.active=mdc-disabled -Pall-quality-gates -B
